# This file is auto generated by FedoraRails.
# 
# In order to include FedoraRails functionality in your ActiveRecord objects, send those objects an
# :include method so they can contain FedoraRails::Concerns::Fedorable functionality  
# 
# For example:
#   YourObject.send :include, FedoraRails::Concerns::Fedorable
['Bag', 'CompressedBag', 'DescriptionObject', 'Institution', 'TransactionalObject'].each do |fedora_class|
  fedora_class.constantize.send :include, Concerns::Fedorable
end
